# input topic name setting ===========> Please change according to your dataset
lidar_topic: "/dreamstep_colored_body"
odom_topic: "/dreamstep_odom"
pose_source: 2
world_frame: "map"

debug_print: true

# Collate meshes for final singular mesh
collate_mesh: true

# Ignore points closer than this value (meters) (default 0.4)
min_scan_range: 0.4

# Ignore points far than this value (meters) (default 12.0)
max_scan_range: 12.0

# Check on paper
sdf_space_carving: true

sdf_trunc: 0.15

# voxel resolution (meters)
sdf_voxel_size: 0.04

# min weight setting TODO add details description
sdf_min_weight: 0.5
sdf_deactivate: 0.05

# Translation
tx: 0
ty: 0
tz: 0
# Rotation Quaternion
x: 0
y: 0
z: 0
w: 1
